# Generated by Django 3.1.5 on 2021-02-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0003_auto_20210126_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=505)),
                ('address', models.CharField(max_length=700)),
                ('state', models.CharField(max_length=700)),
                ('city', models.CharField(max_length=700)),
                ('zip_code', models.CharField(max_length=700)),
            ],
        ),
    ]
