# Generated by Django 3.1.5 on 2021-02-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0005_orders_items_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=7000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
